name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build-extensions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: NPM install
        run: npm ci
      - name: Build content
        run: npm start
      - name: Zip archives
        run: |
          for dir in *
          do
            pushd $dir
              zip -r ../$dir.zip .
            popd
          done
        working-directory: dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: extensions
          path: dist/*.zip

  build-host-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: CMake configure x64
        run: cmake -B build .
        working-directory: native-messaging-host
      - name: CMake build x64
        run: cmake --build build --config MinSizeRel
        working-directory: native-messaging-host
      - name: Upload artifact x64
        uses: actions/upload-artifact@v2
        with:
          name: native-messaging-host-linux-x64
          path: native-messaging-host/build/keeweb-native-messaging-host

  build-host-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: CMake configure x64
        run: cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 -B build .
        working-directory: native-messaging-host
      - name: CMake build x64
        run: cmake --build build --config MinSizeRel
        working-directory: native-messaging-host
      - name: Upload artifact x64
        uses: actions/upload-artifact@v2
        with:
          name: native-messaging-host-darwin-x64
          path: native-messaging-host/build/keeweb-native-messaging-host
      - name: Clean
        run: rm -rf build
        working-directory: native-messaging-host
      - name: CMake configure arm64
        run: cmake -DCMAKE_OSX_ARCHITECTURES=arm64 -B build .
        working-directory: native-messaging-host
      - name: CMake build arm64
        run: cmake --build build --config MinSizeRel
        working-directory: native-messaging-host
      - name: Upload artifact arm64
        uses: actions/upload-artifact@v2
        with:
          name: native-messaging-host-darwin-arm64
          path: native-messaging-host/build/keeweb-native-messaging-host

  build-host-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: CMake configure x64
        run: cmake -B build .
        working-directory: native-messaging-host
      - name: CMake build x64
        run: cmake --build build --config MinSizeRel
        working-directory: native-messaging-host
      - name: Upload artifact x64
        uses: actions/upload-artifact@v2
        with:
          name: native-messaging-host-windows-x64
          path: native-messaging-host/build/keeweb-native-messaging-host.exe
