name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: NPM install
        run: npm ci
      - name: Build extensions
        run: npm start
      - name: Make archives
        run: |
          for dir in *
          do
            pushd $dir
              zip -r ../$dir.zip .
            popd
          done
          ls -la
        working-directory: dist