name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build-extensions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: NPM install
        run: npm ci
      - name: Build content
        run: npm start
      - name: Zip archives
        run: |
          for dir in *
          do
            pushd $dir
              zip -r ../$dir.zip .
            popd
          done
        working-directory: dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: extensions
          path: dist/*.zip
  build-host-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: CMake configure
        run: cmake -B build .
        working-directory: native-messaging-host
      - name: CMake build
        run: cmake --build build --config MinSizeRel
        working-directory: native-messaging-host
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: native-messaging-host-ubuntu-x64
          path: native-messaging-host/build/keeweb-native-messaging-host
