name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:

#  build-extensions:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: NPM install
#        run: npm ci
#      - name: Build content
#        run: npm start
#      - name: Zip archives
#        run: |
#          for dir in *
#          do
#            pushd $dir
#              zip -r ../$dir.zip .
#            popd
#          done
#        working-directory: dist
#      - name: Upload artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: extensions
#          path: dist/*.zip

#  build-host-linux-x64:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: CMake configure
#        run: cmake -B build .
#        working-directory: native-messaging-host
#      - name: CMake build
#        run: cmake --build build --config MinSizeRel
#        working-directory: native-messaging-host
#      - name: Upload artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: native-messaging-host-linux-x64
#          path: native-messaging-host/build/keeweb-native-messaging-host
#
#  build-host-darwin-x64:
#    runs-on: macos-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: CMake configure
#        run: cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 -B build .
#        working-directory: native-messaging-host
#      - name: CMake build
#        run: cmake --build build --config MinSizeRel
#        working-directory: native-messaging-host
#      - name: Upload artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: native-messaging-host-darwin-x64
#          path: native-messaging-host/build/keeweb-native-messaging-host
#
#  build-host-darwin-arm64:
#    runs-on: macos-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: CMake configure
#        run: cmake -DCMAKE_OSX_ARCHITECTURES=arm64 -B build .
#        working-directory: native-messaging-host
#      - name: CMake build
#        run: cmake --build build --config MinSizeRel
#        working-directory: native-messaging-host
#      - name: Upload artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: native-messaging-host-darwin-arm64
#          path: native-messaging-host/build/keeweb-native-messaging-host

  build-host-win32-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: CMake configure
        run: cmake -B build -A x64 .
        working-directory: native-messaging-host
      - name: CMake build
        run: cmake --build build --config MinSizeRel
        working-directory: native-messaging-host
      - name: List
        run: tree native-messaging-host/build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: native-messaging-host-win32-x64
          path: native-messaging-host/build/Release/keeweb-native-messaging-host.exe

#  build-host-win32-ia32:
#    runs-on: windows-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: CMake configure
#        run: cmake -B build -A win32 .
#        working-directory: native-messaging-host
#      - name: CMake build
#        run: cmake --build build --config MinSizeRel
#        working-directory: native-messaging-host
#      - name: Upload artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: native-messaging-host-win32-ia32
#          path: native-messaging-host/build/Release/keeweb-native-messaging-host.exe
#
#  build-host-win32-arm64:
#    runs-on: windows-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: CMake configure
#        run: cmake -B build -A arm64 .
#        working-directory: native-messaging-host
#      - name: CMake build
#        run: cmake --build build --config MinSizeRel
#        working-directory: native-messaging-host
#      - name: Upload artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: native-messaging-host-win32-arm64
#          path: native-messaging-host/build/Release/keeweb-native-messaging-host.exe

  publish-host-package:
    needs:
      - build-host-linux-x64
      - build-host-darwin-x64
      - build-host-darwin-arm64
      - build-host-win32-x64
      - build-host-win32-ia32
      - build-host-win32-arm64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download linux-x64 artifact
        uses: actions/download-artifact@v2
        with:
          name: native-messaging-host-linux-x64
          path: packages/native-messaging-host/linux-x64
      - name: Download darwin-x64 artifact
        uses: actions/download-artifact@v2
        with:
          name: native-messaging-host-darwin-x64
          path: packages/native-messaging-host/darwin-x64
      - name: Download darwin-arm64 artifact
        uses: actions/download-artifact@v2
        with:
          name: native-messaging-host-darwin-arm64
          path: packages/native-messaging-host/darwin-arm64
      - name: Download win32-x64 artifact
        uses: actions/download-artifact@v2
        with:
          name: native-messaging-host-win32-x64
          path: packages/native-messaging-host/win32-x64
      - name: Download win32-ia32 artifact
        uses: actions/download-artifact@v2
        with:
          name: native-messaging-host-win32-ia32
          path: packages/native-messaging-host/win32-ia32
      - name: Download windows-arm64 artifact
        uses: actions/download-artifact@v2
        with:
          name: native-messaging-host-win32-arm64
          path: packages/native-messaging-host/win32-arm64
#      - name: Publish npm package
#        run: |
#          rm -f ~/.npmrc
#          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > ~/.npmrc
#          npm publish packages/native-messaging-host
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
