name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build-extensions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: NPM install
        run: npm ci
      - name: Build content
        run: npm start
      - name: Zip archives
        run: |
          for dir in *
          do
            pushd $dir
              zip -r ../$dir.zip .
            popd
          done
        working-directory: dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Extensions
          path: dist/*.zip